# Generated by Django 4.1.4 on 2023-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartname', models.CharField(max_length=20)),
                ('cartprice', models.IntegerField()),
                ('cartdescription', models.CharField(max_length=50)),
                ('cartimage', models.ImageField(upload_to='Alpha/static/cart')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user.html',
            new_name='user',
        ),
    ]
