# Generated by Django 4.1.4 on 2023-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
