# Generated by Django 4.1.4 on 2023-02-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0006_uploadmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
